# Generated by Django 3.2.4 on 2021-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('school', 'degree', 'field', 'is_completed')},
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('organization', 'designation', 'have_left')},
        ),
    ]
