# Generated by Django 3.2.4 on 2021-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Female', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Committed', 'Committed'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=10),
        ),
    ]
