# Generated by Django 3.2.4 on 2021-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20210617_1004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('id', 'name')},
        ),
    ]
