# Generated by Django 3.2.4 on 2021-06-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0012_auto_20210617_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='UserProfiles/FeedTemplates')),
                ('feed_type', models.CharField(choices=[('register', 'register'), ('add_new_photo', 'add_new_photo'), ('add_new_text', 'add_new_text'), ('add_new_friend', 'add_new_friend')], default='register', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_template', to='user_profile.feedtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
